function caledSigma = calSigma(currentState, value_map, probabilities_map, policy)

    if(currentState(1) == 1 && currentState(2) == 1)
        caledSigma = policy(1,1,3)*probabilities_map(1,1,3)*value_map(1,2) + ...
            policy(1,1,4)*probabilities_map(1,1,4)*value_map(2,1) + ...
            policy(1,1,4)*probabilities_map(1,1,3)*value_map(1,2) + ...
            policy(1,1,3)*probabilities_map(1,1,4)*value_map(2,1);
    elseif(currentState(1) == 1 && currentState(2) == 15)
        caledSigma = policy(1,15,1)*probabilities_map(1,15,1)*value_map(1,14) + ...
            policy(1,15,4)*probabilities_map(1,15,4)*value_map(2,15) + ...
            policy(1,15,4)*probabilities_map(1,15,1)*value_map(1,14) + ...
            policy(1,15,1)*probabilities_map(1,15,4)*value_map(2,15);
    elseif(currentState(1) == 15 && currentState(2) == 1)
        caledSigma = policy(15,1,2)*probabilities_map(15,1,2)*value_map(14,1) + ...
            policy(15,1,3)*probabilities_map(15,1,3)*value_map(15,2) + ...
            policy(15,1,3)*probabilities_map(15,1,2)*value_map(14,1) + ...
            policy(15,1,2)*probabilities_map(15,1,3)*value_map(15,2);
    elseif(currentState(1) == 15 && currentState(2) == 15)
        caledSigma = policy(15,15,2)*probabilities_map(15,15,2)*value_map(14,15) + ...
            policy(15,15,1)*probabilities_map(15,15,1)*value_map(15,14) + ...
            policy(15,15,1)*probabilities_map(15,15,2)*value_map(14,15) + ...
            policy(15,15,2)*probabilities_map(15,15,1)*value_map(15,14);
    elseif(currentState(1) == 1)
        caledSigma = ...
            policy(currentState(1),currentState(2),3)*...
            probabilities_map(currentState(1),currentState(2),3)*...
            value_map(currentState(1),currentState(2)+1) + ...
            ...
            policy(currentState(1),currentState(2),1)*...
            probabilities_map(currentState(1),currentState(2),1)*...
            value_map(currentState(1),currentState(2)-1) + ...
            ...
            policy(currentState(1),currentState(2),4)*...
            probabilities_map(currentState(1),currentState(2),4)*...
            value_map(currentState(1)+1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),1)*...
            probabilities_map(currentState(1),currentState(2),3)*...
            value_map(currentState(1),currentState(2)+1) + ...
            ...
            policy(currentState(1),currentState(2),4)*...
            probabilities_map(currentState(1),currentState(2),3)*...
            value_map(currentState(1),currentState(2)+1) + ...
            ...
            policy(currentState(1),currentState(2),3)*...
            probabilities_map(currentState(1),currentState(2),1)*...
            value_map(currentState(1),currentState(2)-1) + ...
            ...
            policy(currentState(1),currentState(2),4)*...
            probabilities_map(currentState(1),currentState(2),1)*...
            value_map(currentState(1),currentState(2)-1) + ...
            ...
            policy(currentState(1),currentState(2),1)*...
            probabilities_map(currentState(1),currentState(2),4)*...
            value_map(currentState(1)+1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),3)*...
            probabilities_map(currentState(1),currentState(2),4)*...
            value_map(currentState(1)+1,currentState(2));
    elseif(currentState(1) == 15)
        caledSigma = ...
            policy(currentState(1),currentState(2),3)*...
            probabilities_map(currentState(1),currentState(2),3)*...
            value_map(currentState(1),currentState(2)+1) + ...
            ...
            policy(currentState(1),currentState(2),1)*...
            probabilities_map(currentState(1),currentState(2),3)*...
            value_map(currentState(1),currentState(2)+1) + ...
            ...
            policy(currentState(1),currentState(2),2)*...
            probabilities_map(currentState(1),currentState(2),3)*...
            value_map(currentState(1),currentState(2)+1) + ...
            ...
            policy(currentState(1),currentState(2),1)*...
            probabilities_map(currentState(1),currentState(2),1)*...
            value_map(currentState(1),currentState(2)-1) + ...
            ...
            policy(currentState(1),currentState(2),2)*...
            probabilities_map(currentState(1),currentState(2),1)*...
            value_map(currentState(1),currentState(2)-1) + ...
            ...
            policy(currentState(1),currentState(2),3)*...
            probabilities_map(currentState(1),currentState(2),1)*...
            value_map(currentState(1),currentState(2)-1) + ...
            ...
            policy(currentState(1),currentState(2),2)*...
            probabilities_map(currentState(1),currentState(2),2)*...
            value_map(currentState(1)-1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),1)*...
            probabilities_map(currentState(1),currentState(2),2)*...
            value_map(currentState(1)-1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),3)*...
            probabilities_map(currentState(1),currentState(2),2)*...
            value_map(currentState(1)-1,currentState(2));
    elseif(currentState(2) == 1)
        caledSigma = ...
            policy(currentState(1),currentState(2),2)*...
            probabilities_map(currentState(1),currentState(2),2)*...
            value_map(currentState(1)-1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),4)*...
            probabilities_map(currentState(1),currentState(2),2)*...
            value_map(currentState(1)-1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),3)*...
            probabilities_map(currentState(1),currentState(2),2)*...
            value_map(currentState(1)-1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),4)*...
            probabilities_map(currentState(1),currentState(2),4)*...
            value_map(currentState(1)+1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),2)*...
            probabilities_map(currentState(1),currentState(2),4)*...
            value_map(currentState(1)+1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),3)*...
            probabilities_map(currentState(1),currentState(2),4)*...
            value_map(currentState(1)+1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),3)*...
            probabilities_map(currentState(1),currentState(2),3)*...
            value_map(currentState(1),currentState(2)+1) + ...
            ...
            policy(currentState(1),currentState(2),2)*...
            probabilities_map(currentState(1),currentState(2),3)*...
            value_map(currentState(1),currentState(2)+1) + ...
            ...
            policy(currentState(1),currentState(2),4)*...
            probabilities_map(currentState(1),currentState(2),3)*...
            value_map(currentState(1),currentState(2)+1);
    elseif(currentState(2) == 15)
        caledSigma = ...
            policy(currentState(1),currentState(2),2)*...
            probabilities_map(currentState(1),currentState(2),2)*...
            value_map(currentState(1)-1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),4)*...
            probabilities_map(currentState(1),currentState(2),2)*...
            value_map(currentState(1)-1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),1)*...
            probabilities_map(currentState(1),currentState(2),2)*...
            value_map(currentState(1)-1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),4)*...
            probabilities_map(currentState(1),currentState(2),4)*...
            value_map(currentState(1)+1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),2)*...
            probabilities_map(currentState(1),currentState(2),4)*...
            value_map(currentState(1)+1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),1)*...
            probabilities_map(currentState(1),currentState(2),4)*...
            value_map(currentState(1)+1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),1)*...
            probabilities_map(currentState(1),currentState(2),1)*...
            value_map(currentState(1),currentState(2)-1) + ...
            ...
            policy(currentState(1),currentState(2),2)*...
            probabilities_map(currentState(1),currentState(2),1)*...
            value_map(currentState(1),currentState(2)-1) + ...
            ...
            policy(currentState(1),currentState(2),4)*...
            probabilities_map(currentState(1),currentState(2),1)*...
            value_map(currentState(1),currentState(2)-1);
    else
        caledSigma = ...
            policy(currentState(1),currentState(2),2)*...
            probabilities_map(currentState(1),currentState(2),2)*...
            value_map(currentState(1)-1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),1)*...
            probabilities_map(currentState(1),currentState(2),2)*...
            value_map(currentState(1)-1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),3)*...
            probabilities_map(currentState(1),currentState(2),2)*...
            value_map(currentState(1)-1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),4)*...
            probabilities_map(currentState(1),currentState(2),2)*...
            value_map(currentState(1)-1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),4)*...
            probabilities_map(currentState(1),currentState(2),4)*...
            value_map(currentState(1)+1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),1)*...
            probabilities_map(currentState(1),currentState(2),4)*...
            value_map(currentState(1)+1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),2)*...
            probabilities_map(currentState(1),currentState(2),4)*...
            value_map(currentState(1)+1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),3)*...
            probabilities_map(currentState(1),currentState(2),4)*...
            value_map(currentState(1)+1,currentState(2)) + ...
            ...
            policy(currentState(1),currentState(2),1)*...
            probabilities_map(currentState(1),currentState(2),1)*...
            value_map(currentState(1),currentState(2)-1) + ...
            ...
            policy(currentState(1),currentState(2),2)*...
            probabilities_map(currentState(1),currentState(2),1)*...
            value_map(currentState(1),currentState(2)-1) + ...
            ...
            policy(currentState(1),currentState(2),3)*...
            probabilities_map(currentState(1),currentState(2),1)*...
            value_map(currentState(1),currentState(2)-1) + ...
            ...
            policy(currentState(1),currentState(2),4)*...
            probabilities_map(currentState(1),currentState(2),1)*...
            value_map(currentState(1),currentState(2)-1) + ...
            ...
            policy(currentState(1),currentState(2),3)*...
            probabilities_map(currentState(1),currentState(2),3)*...
            value_map(currentState(1),currentState(2)+1) + ...
            ...
            policy(currentState(1),currentState(2),1)*...
            probabilities_map(currentState(1),currentState(2),3)*...
            value_map(currentState(1),currentState(2)+1) + ...
            ...
            policy(currentState(1),currentState(2),2)*...
            probabilities_map(currentState(1),currentState(2),3)*...
            value_map(currentState(1),currentState(2)+1) + ...
            ...
            policy(currentState(1),currentState(2),4)*...
            probabilities_map(currentState(1),currentState(2),3)*...
            value_map(currentState(1),currentState(2)+1);
    end
end